AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Civic Mirror Backend - FastAPI application deployed on AWS Lambda

Parameters:
  AWSBucketName:
    Type: String
    Description: "S3 bucket name"
    
  AWSCloudfrontUrl:
    Type: String
    Description: "CloudFront URL"
    
  TwilioAccountSID:
    Type: String
    Description: "Twilio Account SID"
    
  TwilioAuthToken:
    Type: String
    Description: "Twilio Auth Token"
    NoEcho: true
    
  TwilioPhoneNumber:
    Type: String
    Description: "Twilio Phone Number"
    
  SecretKey:
    Type: String
    Description: "Secret key for JWT signing"
    NoEcho: true
    
  DatabaseURL:
    Type: String
    Description: "Database connection URL"
    NoEcho: true

  PusherAppId:
    Type: String
    Description: "Pusher App ID"

  PusherKey:
    Type: String
    Description: "Pusher Key"

  PusherSecret:
    Type: String
    Description: "Pusher Secret"

  PusherCluster:
    Type: String
    Description: "Pusher Cluster"

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.11
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - Statement:
            - Effect: "Allow"
              Action:
                - "ssm:GetParameter"
                - "ssm:GetParameters"
                - "ssm:GetParametersByPath"
              Resource: "arn:aws:ssm:ap-south-1:*:parameter/civicmirror/*"
        - Statement:
            - Effect: "Allow"
              Action:
                - "s3:PutObject"
                - "s3:GetObject"
                - "s3:DeleteObject"
                - "s3:ListBucket"
              Resource: 
                - !Sub "arn:aws:s3:::${AWSBucketName}"
                - !Sub "arn:aws:s3:::${AWSBucketName}/*"
      Environment:
        Variables:
          ENVIRONMENT: "production"
          AWS_BUCKET_NAME: !Ref AWSBucketName
          AWS_CLOUDFRONT_URL: !Ref AWSCloudfrontUrl
          CUSTOM_AWS_REGION: "ap-south-1"
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSID
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber
          SECRET_KEY: !Ref SecretKey
          DATABASE_URL: !Ref DatabaseURL
          PUSHER_APP_ID: !Ref PusherAppId
          PUSHER_KEY: !Ref PusherKey
          PUSHER_SECRET: !Ref PusherSecret
          PUSHER_CLUSTER: !Ref PusherCluster
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
            RestApiId: !Ref CivicMirrorApiGateway

  CivicMirrorApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "Prod"
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With'"
        AllowOrigin: "'*'"
        AllowCredentials: "'true'"
      BinaryMediaTypes:
        - image/jpeg
        - image/png
        - application/octet-stream
        - image/webp
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With'"
              Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,PATCH,DELETE'"
              Access-Control-Allow-Credentials: "'true'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With'"
              Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,PATCH,DELETE'"
              Access-Control-Allow-Credentials: "'true'"

Outputs:
  ApiGatewayUrl:
    Value: !Sub 'https://${CivicMirrorApiGateway}.execute-api.ap-south-1.amazonaws.com/Prod/'
    Description: The URL of the API Gateway
